package me.saket.telephoto.subsamplingimage.internal

import android.graphics.BitmapFactory
import android.graphics.BitmapRegionDecoder
import android.os.Build
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.graphics.toAndroidRect
import androidx.compose.ui.unit.IntOffset
import androidx.compose.ui.unit.IntRect
import androidx.compose.ui.unit.IntSize
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.withContext
import me.saket.telephoto.subsamplingimage.ImageBitmapOptions
import me.saket.telephoto.subsamplingimage.SubSamplingImageSource
import me.saket.telephoto.subsamplingimage.internal.ExifMetadata.ImageOrientation
import me.saket.telephoto.subsamplingimage.toAndroidConfig

/** Bitmap decoder backed by Android's [BitmapRegionDecoder]. */
internal class AndroidImageRegionDecoder private constructor(
  private val context: android.content.Context,
  private val imageSource: SubSamplingImageSource,
  private val imageOptions: ImageBitmapOptions,
  private var decoder: BitmapRegionDecoder,
  private val exif: ExifMetadata,
  private val dispatcher: CoroutineDispatcher,
) : ImageRegionDecoder {
 
  override val imageSize: IntSize get() = decoder.size()
 
  override suspend fun decodeRegion(region: ImageRegionTile): Painter {
    val options = BitmapFactory.Options().apply {
      inSampleSize = region.sampleSize.size
      inPreferredConfig = imageOptions.config.toAndroidConfig()
      if (Build.VERSION.SDK_INT >= 26) {
        inPreferredColorSpace = imageOptions.androidColorSpace
      }
    }
 
    val bounds = region.bounds.rotateBy(
      // Rotation of images is transparent to consumers of ImageRegionDecoder.
      // When tiles are generated by SubSamplingImage, it assumes that the image is
      // already in the correct orientation. To counter this, rotate the bounds in
      // anticlockwise direction to get the bounds in the original non-rotated image.
      degrees = -exif.orientation.degrees,
      unRotatedParent = IntRect(offset = IntOffset.Zero, size = imageSize)
    )

    val tileFileName = "tile_${imageSource.toString().hashCode()}_l${bounds.left}_t${bounds.top}_r${bounds.right}_b${bounds.bottom}_s${region.sampleSize.size}.jpg"
    val cacheDir = java.io.File(context.cacheDir, "tile_cache")
    val cacheFile = java.io.File(cacheDir, tileFileName)
 
    val bitmap = withContext(dispatcher) {
      var decoded: android.graphics.Bitmap? = null
      if (cacheDir.exists() && cacheFile.exists()) {
        try {
          decoded = android.graphics.BitmapFactory.decodeFile(cacheFile.absolutePath)
        } catch (e: Exception) {
          android.util.Log.e("TileCache", "Failed to decode cached tile: ${cacheFile.name}", e)
        }
      }

      if (decoded == null) {
        try {
          decoded = decoder.decodeRegion(bounds.toAndroidRect(), options)
        } catch (e: Exception) {
          android.util.Log.e("AndroidImageRegionDecoder", "Failed to decode region, will attempt to recreate decoder", e)
        }

        if (decoded == null) {
          try {
            android.util.Log.i("AndroidImageRegionDecoder", "Recreating decoder for source: $imageSource")
            val newDecoder = imageSource.decoder(context)
            try {
              decoder.recycle()
            } catch (ignored: Exception) {}
            decoder = newDecoder
            decoded = decoder.decodeRegion(bounds.toAndroidRect(), options)
          } catch (recreateEx: Exception) {
            android.util.Log.e("AndroidImageRegionDecoder", "Failed to recreate decoder and decode region", recreateEx)
          }
        }

        if (decoded != null) {
          try {
            if (!cacheDir.exists()) {
              cacheDir.mkdirs()
            }
            java.io.FileOutputStream(cacheFile).use { out ->
              decoded.compress(android.graphics.Bitmap.CompressFormat.JPEG, 85, out)
            }
          } catch (e: Exception) {
            android.util.Log.e("TileCache", "Failed to save tile cache: ${cacheFile.name}", e)
          }
        }
      }

      if (decoded != null && com.pixel.gallery.data.repository.LargeImagePerformanceConfig.useHardwareBitmap) {
        try {
          decoded.copy(android.graphics.Bitmap.Config.HARDWARE, false).also {
            decoded.recycle()
          }
        } catch (e: Exception) {
          decoded
        }
      } else {
        decoded
      }
    }
    if (bitmap != null) {
      return RotatedBitmapPainter(
        image = bitmap,
        orientation = exif.orientation,
      )
    } else {
      error("BitmapRegionDecoder returned a null bitmap. Image format may not be supported: $imageSource.")
    }
  }
 
  override fun close() {
    try {
      decoder.recycle()
    } catch (ignored: Exception) {}
  }
 
  private fun BitmapRegionDecoder.size(): IntSize {
    val shouldFlip = when (exif.orientation) {
      ImageOrientation.Orientation90,
      ImageOrientation.Orientation270 -> true
      else -> false
    }
 
    return IntSize(
      width = if (shouldFlip) height else width,
      height = if (shouldFlip) width else height,
    )
  }
 
  companion object {
    @OptIn(ExperimentalCoroutinesApi::class)
    val Factory = ImageRegionDecoder.Factory { params ->
      val dispatcher = com.pixel.gallery.data.repository.LargeImagePerformanceConfig.decoderDispatcher
 
      AndroidImageRegionDecoder(
        context = params.context,
        imageSource = params.imageSource,
        imageOptions = params.imageOptions,
        decoder = withContext(dispatcher) {
          params.imageSource.decoder(params.context)
        },
        exif = params.exif,
        dispatcher = dispatcher,
      )
    }
  }
}
